[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "geomagnetic"
version = "0.1.0"
dependencies = ["numpy", "pytest"]
authors = [{name = "Shunsuke"}]
description = "module for geomagnetic calculation"